// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcG36u7KWUdTPS4_932nji65Fy7bcOAok',
    appId: '1:1088814273596:web:65b264ed95a73a2ba05f39',
    messagingSenderId: '1088814273596',
    projectId: 'aweto-app',
    authDomain: 'aweto-app.firebaseapp.com',
    databaseURL: 'https://aweto-app-default-rtdb.firebaseio.com',
    storageBucket: 'aweto-app.appspot.com',
    measurementId: 'G-JTZ3KLHTG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzxX6MYDly3av5hZemLnfiZu5jIp1YuE',
    appId: '1:1088814273596:android:86bed910e72ba8f8a05f39',
    messagingSenderId: '1088814273596',
    projectId: 'aweto-app',
    databaseURL: 'https://aweto-app-default-rtdb.firebaseio.com',
    storageBucket: 'aweto-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ0Sw4jeH_CP6NEC2_3J5Fuz6iSbco0AY',
    appId: '1:1088814273596:ios:6e0a5b1dfcdb3612a05f39',
    messagingSenderId: '1088814273596',
    projectId: 'aweto-app',
    databaseURL: 'https://aweto-app-default-rtdb.firebaseio.com',
    storageBucket: 'aweto-app.appspot.com',
    iosBundleId: 'com.example.awetoUserApp',
  );
}
